version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: dockerfile
      target: production
    volumes:
      - ./locales:/home/node/app/locales
      - ./src:/home/node/app/src
    container_name: kiera-bot
    restart: on-failure
    command: npm run start
    environment:
      NODE_ENV: production
