version: '3.9'

secrets:
  BOT_WEB_APP_SERVER_SECRET:
    file: ./secrets/BOT_WEB_APP_SERVER_SECRET
  CK_CLIENTID:
    file: ./secrets/CK_CLIENTID
  CK_CLIENTSECRET:
    file: ./secrets/CK_CLIENTSECRET
  CK_RAPIDAPIKEY:
    file: ./secrets/CK_RAPIDAPIKEY
  DB_STRING:
    file: ./secrets/DB_STRING
  DISCORD_APP_SECRET:
    file: ./secrets/DISCORD_APP_SECRET
  DISCORD_APP_TOKEN:
    file: ./secrets/DISCORD_APP_TOKEN

services:
  bot:
    build:
      context: .
      dockerfile: dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: kiera_bot
    ports:
      - '8124:8124'
    expose:
      - '8124'
    command: npm run dev
    restart: on-failure
    secrets:
      - BOT_WEB_APP_SERVER_SECRET
      - CK_CLIENTID
      - CK_CLIENTSECRET
      - CK_RAPIDAPIKEY
      - DB_STRING
      - DISCORD_APP_SECRET
      - DISCORD_APP_TOKEN
    environment:
      NODE_ENV: development